Remove the rustfmt step from CI because it no longer works.
I can't figure out how to fix the errors like:
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not have the binary `cargo-fmt`
and rustfmt-nightly doesn't seem to work with stable rust.