Revert "Update dependencies and bump version to 0.4.7."
This reverts commit 0b9dfe578e01f1bdd1abebe1602da6ee07aad9cf,
because it caused:
  thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.'
when the IRC bot tried to repond on real IRC connections.